// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukfdNURQ1dzbJphO_cSah1qVwZ3HVyBU',
    appId: '1:706909088375:web:963c9be8552437f75cf472',
    messagingSenderId: '706909088375',
    projectId: 'melmar-7cad9',
    authDomain: 'melmar-7cad9.firebaseapp.com',
    storageBucket: 'melmar-7cad9.firebasestorage.app',
    measurementId: 'G-0BGQJ3PR92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOjndVg7x6HMfwyfqhyd7Bn23diG5c6gY',
    appId: '1:706909088375:android:553d97a323809e295cf472',
    messagingSenderId: '706909088375',
    projectId: 'melmar-7cad9',
    storageBucket: 'melmar-7cad9.firebasestorage.app',
  );

}